development:
  adapter: postgresql
  database: roelspits_dev
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: roelspits_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: roelspits_prod
  pool: 5
  timeout: 5000
